#!/bin/sh
CARD=$(iw dev | awk '/Interface/ {print $2}')
USER_L=$(whoami)
scan="$(DISPLAY=$DISPLAY notify-send "Scanning")"


NUM="$((iw dev "$CARD" scan | grep SSID | sed 's/\\\S//gi;s/^d0\Ss//gi' | awk -F': ' '{print $2}' && echo "disconnect" && echo "forget" && killall dunst) | su $USER_L -c "DISPLAY=$DISPLAY dmenu -i -p \"What network do you want to connect to?\" -l 10")"

check="$(for file in /etc/wpa_supplicant/*; do printf '%s\n' "$file"; done | grep "$NUM")"


if [ -n $NUM ] && [ -z $check ] && [ $NUM != "disconnect" ] && [ $NUM != "forget" ] ; then
	pass=$("$1" | su $USER_L -c "DISPLAY=$DISPLAY dmenu -i -p \"Type the password.\""); 
	[ -z $pass ] && exit 1
	if [ -n $pass ] ; then
		touch /etc/wpa_supplicant/"$NUM".conf;echo "ctrl_interface=/run/wpa_supplicant" \
			>> /etc/wpa_supplicant/"$NUM".conf ; echo "update_config=1" \
			>> /etc/wpa_supplicant/"$NUM".conf ; wpa_passphrase "$NUM" "$pass" \
			>> /etc/wpa_supplicant/"$NUM".conf ;
					wpa_supplicant -B -i $CARD -c /etc/wpa_supplicant/$NUM.conf
	fi
elif [ -n "$check" ] && [ "$NUM" != "disconnect" ] && [ "$NUM" != "forget" ]; then
	wpa_supplicant -B -i "$CARD" -c $check
elif [ "$NUM" = "disconnect" ]; then
	killall wpa_supplicant
elif [ "$NUM" = "forget" ]; then
	to_forget="$(for file in /etc/wpa_supplicant/*; do printf '%s\n' "$file"; done | sed 's/.conf//' | su $USER_L -c "DISPLAY=$DISPLAY dmenu -i -p \"What network do you want to forget?\" -l 10")"
	rm $to_forget.conf
	killall wpa_supplicant 
else exit 0
fi


